updated deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,13 +25,13 @@ jobs:
           ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts 2>/dev/null
 
       - name: Set deployment environment variables
+        run: |
+          if [ -z "${{ vars.DEPLOY_PATH }}" ] || [ -z "${{ vars.ENV }}" ]; then
+            echo "Error: Environment variables DEPLOY_PATH or ENV are not set."; exit 1
+          fi
         env:
           DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}
           ENV: ${{ vars.ENV }}
-        run: |
-          if [ -z "$DEPLOY_PATH" ] || [ -z "$ENV" ]; then
-            echo "Error: Environment variables not set."; exit 1
-          fi
 
       - name: Debug Environment Variables
         run: |
@@ -49,44 +49,30 @@ jobs:
           DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}
           ENV: ${{ vars.ENV }}
         run: |
-          echo "Using DEPLOY_PATH: $DEPLOY_PATH"  # Verificar el valor localmente
-          ssh -i /home/runner/.ssh/id_rsa -p $SSH_PORT -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST << EOF
-            # Definir manualmente DEPLOY_PATH y ENV en la sesión SSH
-            DEPLOY_PATH="${{ env.DEPLOY_PATH }}"
-            ENV="${{ env.ENV }}"
+          echo "Using DEPLOY_PATH: $DEPLOY_PATH"
+          ssh -i ~/.ssh/id_rsa -p "$SSH_PORT" -o StrictHostKeyChecking=no "$SSH_USERNAME@$SSH_HOST" << 'EOF'
+            DEPLOY_PATH="${DEPLOY_PATH}"
+            ENV="${ENV}"
 
-            # Mostrar el nombre del servidor y la carpeta actual
             echo "Logged into server: $(hostname)"
-            echo "Current directory before cd: $(pwd)"  # Mostrar el directorio actual
+            echo "Current directory before cd: $(pwd)"
 
-            # Verificar el valor de DEPLOY_PATH
-            echo "DEPLOY_PATH is: $DEPLOY_PATH"
-
-            # Intentar cambiar al directorio de despliegue
             cd "$DEPLOY_PATH" || { echo "Failed to change to DEPLOY_PATH"; exit 1; }
-
-            # Verificar si el cambio de directorio fue exitoso
-            echo "Changed to directory: $(pwd)"  # Mostrar la ruta del directorio de despliegue
+            echo "Changed to directory: $(pwd)"
 
             if [ -d ".git" ]; then
               echo "Git repository detected."
-
-              # Resetear todos los cambios locales en archivos rastreados
               echo "Resetting all local changes..."
-              git reset --hard HEAD  # Restablecer todos los cambios locales en archivos rastreados
+              git reset --hard HEAD
+              git remote -v
+              git status
 
-              git remote -v  # Verificar el repositorio remoto
-              git status  # Verificar el estado del repositorio local
-
-              # Realizar fetch y pull de la rama correspondiente
-              git fetch origin "$ENV" && git pull origin "$ENV"  # Obtener los cambios del repositorio remoto
+              git fetch origin "$ENV" && git pull origin "$ENV"
             else
               echo "Error: Not a git repository or missing .git folder."
               exit 1
             fi
 
-            # Ejecutar el script de inicio de contenedores
             chmod +x start_containers.sh &&
             ./start_containers.sh "$ENV"
           EOF
-
